spring.application.name=doculens

spring.datasource.url=jdbc:postgresql://localhost:5432/doculens
spring.datasource.username=${DB_USERNAME:shiva}
spring.datasource.password=${DB_PASSWORD:shiva@18}
spring.datasource.driver-class-name=org.postgresql.Driver

management.otlp.metrics.export.enabled=false