spring.application.name=doculens

# DevTools - auto reload on code change
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true
spring.devtools.restart.poll-interval=2s
spring.devtools.restart.quiet-period=1s

spring.datasource.url=jdbc:postgresql://localhost:5432/doculens
spring.datasource.username=${DB_USERNAME:shiva}
spring.datasource.password=${DB_PASSWORD:shiva@18}
spring.datasource.driver-class-name=org.postgresql.Driver

management.otlp.metrics.export.enabled=false


rustfs.endpoint=http://localhost:9000
rustfs.access-key=admin
rustfs.secret-key=admin
rustfs.bucket=doculens
rustfs.region=ap-south-1


spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=500MB


#Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
